### ISSUE TITLE
issue with pmag.magic_read() while developing ipmag.dmag_magic()

### ISSUE THREAD

**Issue by lfairchild** [PmagPy/2016_Tauxe-et-al_PmagPy_Notebooks#2]
I've developed some code in the notebook for a new ipmag implementation of the dmag_magic function. My code keeps throwing an error after calling pmag.magic_read() to read the example data file. It appears that "readline" is not working properly when I call pmag.magic_read (instead of reading the first line of the file, it simply returns a left curly bracket(??)), although when I explicitly pass the same magic_read code into the notebook it works fine. Many of the other functions in the notebook call pmag.magic_read() with no problems, so I'm puzzled. Although it looks okay, I'm thinking that there must be some issue with the format or raw text of the example data file (PmagPy_Datafiles/dmag_magic/dmag_magic_example.dat), even though the same open()...readline() code that magic_read uses works fine in the notebook. Any ideas?

**Comment by Swanson-Hysell** [comment]
Since the issue could be with the example data file, I would suggest
focusing on using a current data file for this function (you could try the
2014 Osler data for example). If the function is working on other magic
files that you pull in from the database, it may be that there is an issue
with the .dat file in the example files and that it could potentially be
replaced.

**Comment by lfairchild** [comment]
Fixed -- there was an inconspicuous conflict I missed in the code block. Both datasets appear to work fine now.
