### ISSUE TITLE
cosmetic figure edits to additional examples notebook suggested by Rupert

### ISSUE THREAD

**Issue by Swanson-Hysell** [PmagPy/2016_Tauxe-et-al_PmagPy_Notebooks#8]
Here are a few cosmetic figure edits suggested by @rminnett via email in which he used the cell execution index notebook to refer to the cells. I have put in some associated notes in _italic_.

1)      Perhaps the x axis ticks and labels could be more spread out on the cumulative distribution plots for cell 21. Or the plots could be bigger like the ones in cell 33, although they, too, sometimes have overlapping x labels.

_NSH Note: The ipmag.reversal_test_bootstrap CDFs are the ones being referred to._

2)      Maybe the figure boundaries around the equal area plots in general could be tighter since they don’t have x and y labels (e.g. compare white space around the figures in cell 20 and 23).

_NSH Note: We have done a fair amount to reduce the white space around the equal area plots (it used to be much greater). I think it is ok as is, but it makes sense to have a look at again._

3)      Can data points in the plots in cells 5 and 6 get obscured by the legend? Perhaps the legend should be below the plot since it could have multiple rows in it.

_NSH Note: In the case of this specific plot, they won't be obscured. However, in similar types of plots they could be. So it might make sense to have an example that shows how you can make a figure legend be outside of the plot itself using bbox to anchor._

**Comment by lfairchild** [comment]
Working on these fixes now. One quick cosmetic solution I just implemented was switching the inline backend back to svg (I commented that out earlier so things could move a little faster in the notebook while I was working). I just synced this to the main repo -- however, the nbviewer is still not reflecting this update. Does it just take a little while to update, or am I missing a step somewhere?

**Comment by lfairchild** [comment]
Oh never mind, it just now changed. It looks like this might partially resolve some of these issues but not entirely. I'll keep working on things and keep you updated.

**Comment by Swanson-Hysell** [comment]
Good deal. Keeping at SVG makes sense as that is how we optimized the figure sizes...and they look a lot nicer that way. For some reason, the SVGs don't seem to render when you open a downloaded notebook and need to be regenerated. But given that they render nicely on nbviewer and look so sharp keeping that format makes sense.

@lfairchild you want to take a look at moving one of the legends for the IGRF equal area plots outside of the plot to demonstrate that functionality? 

And this Stack Overflow could be helpful for the xaxis ticks on the CDFs: http://stackoverflow.com/questions/6682784/how-to-reduce-number-of-ticks-with-matplotlib
`pyplot.locator_params(axis = 'x', nbins = 4)`

**Comment by lfairchild** [comment]
Most of these issues should now be fixed. 

The excess white space definitely seems a little harder to resolve. Thankfully, with the format now switched to SVG, it doesn't seem to be much of a problem. The plots that could definitely use some trimming are the reversal test outputs -- however, this could be a little trickier because the equal area plot and the CDFs are being plotted in two separate functions (former in the reversal test function, the latter in the common mean function). They are therefore being treated as separate figures rather than subplots of the same figure (which could possibly be adjusted to minimize white space using plt.subplot_adjust). Feel free to let me know if you have any ideas about this or any other cosmetic changes that should be made. If not, I think this issue could be closed for now.
